---
title: "Benchmarking FDR Methods - Alternative Settings"
author: "Rafalab Journal Club Members"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    highlight: tango
    number_sections: true
    code_folding: hide
---

<!-- ######################################################################## -->
<!-- preliminaries                                                            --> 
<!-- ######################################################################## -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, install-benchmarked-methods, eval=FALSE}
## from CRAN
install.packages("ashr")

## from Bioconductor
BiocInstaller::biocLite("IHW")
BiocInstaller::biocLite("qvalue")
BiocInstaller::biocLite("swfdr")

## from GitHub
devtools::install_github('jgscott/FDRreg', subdir="R_pkg/")
devtools::install_github("nignatiadis/IHWpaper")
```


<!-- ######################################################################## -->
## Workspace Setup
<!-- ######################################################################## -->

```{r, load-libraries, message=FALSE}
library("dplyr")
library("ggplot2")
library("data.table")
library("SummarizedBenchmark")
```

```{r, load-helper-functions}
source("analysis-01-plotters.R")
source("../datasets/R/evaluation-helpers.R")
```

<!-- ######################################################################## -->
## Plot Performance Metrics (100 replications)
<!-- ######################################################################## -->

```{r}
## list of results from 100 replication experiments
fl <- list.files("data", pattern="results-.*-M100.RDS", full.names=TRUE)

## generate same plots for all parameter settings
for (f in fl) {
    ## read process data
    res <- readRDS(f)
    tsb <- standardize_results(res, alpha = seq(0.01, 0.10, 0.01))
    tsbs <- tsb %>%
        filter(!(blabel %in% c("bl-df02", "bl-df04", "bl-df05", "bonf"))) 

    ## look at FPR for Boca-Leek variations
    gp <- tsb %>%
        filter(grepl("^bl-", blabel)) %>%
        average_plots("FPR")
    ggsave(paste0("plots/FPR-bocaleek-",
                  gsub("(.*)\\.RDS", "\\1", basename(f)), ".png"), gp,
           width=7, height=6, units="in", dpi=200)
    
    ## look at FPR for IHW variations
    gp <- tsb %>%
        filter(grepl("^ihw-", blabel)) %>%
        average_plots("FPR", merge_ihw = FALSE)
    ggsave(paste0("plots/FPR-ihw-",
                  gsub("(.*)\\.RDS", "\\1", basename(f)), ".png"), gp,
           width=7, height=6, units="in", dpi=200)
    
    ## make plots for all metrics
    for (im in unique(tsbs$performanceMetric)) {
        gp <- average_plots(tsbs, im, clean_names = TRUE)
        ggsave(paste0("plots/", im, "-", gsub("(.*)\\.RDS", "\\1", basename(f)), ".png"), gp,
               width=7, height=6, units="in", dpi=200)
    }
}
```


<!-- ######################################################################## -->
## Plot Adjusted P-Values (1 replication)
<!-- ######################################################################## -->

```{r}
## list of results from 1 replication experiments
fl <- list.files("data", pattern = "results-.*-M1.rdata", full.names = TRUE)

## generate same plots for all parameter settings
for (f in fl) {
    ## read process data
    load(f)
    sba <- data.frame(assay(sb))

    ## for plots, only interested in Boca-Leek w/ 3 dof, IHw w/ alpha=0.05
    sbas <- select(sba, -c(`bl.df02`, `bl.df04`, `bl.df05`, `bonf`,
                           `ihw.a01`:`ihw.a04`, `ihw.a06`:`ihw.a10`))

    ## adjusted p-values vs. effect size
    gp <- single_plots(sbas, sim_df, "effect_size", TRUE)
    ggsave(paste0("plots/effectsize-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
           gp, width=10, height=9, units="in", dpi=200)

    ## adjusted p-values vs. independent covariate (uniformative)
    gp <- single_plots(sbas, sim_df, "ind_covarate", TRUE)
    ggsave(paste0("plots/indcov-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
           gp, width=10, height=9, units="in", dpi=200)

    ## adjusted p-values vs. standard error
    gp <- single_plots(sbas, sim_df, "SE", TRUE)
    ggsave(paste0("plots/SE-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
           gp, width=10, height=9, units="in", dpi=200)
}
```





