---
title: "R Notebook"
output: html_notebook
---
```{r}
# Load packageas and source benchmark FDR
library(data.table)
library(readxl)
library(dplyr)
library(ggplot2)
library(magrittr)
library(R.utils)
library(cowplot)

# benchmark methods
library(IHW)
library(ashr)
library(qvalue)
library(swfdr)
library(fdrtool)
library(FDRreg)

# comparison tools/functions
library(SummarizedBenchmark)
sourceDirectory("~/Documents/Research/benchmark-fdr/datasets/R/")

# set up parallel backend
library(BiocParallel)
cores <- 4
multicoreParam <- MulticoreParam(workers = cores)

```


```{r}
#Load expression data
load('~/Documents/Research/benchmark-fdr/datasets/RNA-Seq/dsdObjects.RData')

#Filter to include samples from only 2 tissuesdsd
filteredDsd1 <- dsd1[,colData(dsd1)$tissue %in% c('Brain - Nucleus accumbens (basal ganglia)','Brain - Putamen (basal ganglia)')]
filteredDsd1$tissue <- droplevels(filteredDsd1$tissue)

#Buid DESeq object and run DESeq2
dds <- DESeq(filteredDsd1, parallel = T) # This step can take a few minutes since we have many samples
res <- results(dds, independentFiltering = F)

#Build input data frame for summarized benchmark
#Important to not change col names since SB is strict about that
geneExp <- tbl_df(data.frame(geneName=rownames(res), pval=res$pvalue, SE=res$lfcSE, 
                      ind_covariate = res$baseMean, effect_size=res$log2FoldChange, test_statistic=res$stat))

geneExp <- geneExp %>% na.omit() %>% dplyr::filter(ind_covariate>=1)

```

```{r}
strat_hist(geneExp, pvalue="pval", covariate="ind_covariate", maxy=25)
```

```{r}
rank_scatter(geneExp, pvalue="pval", covariate="ind_covariate")
```

```{r}
bd <- initializeBenchDesign()
sb <- bd %>% buildBench(data=geneExp, parallel = T)

assayNames(sb) <- "qvalue"
sb <- addDefaultMetrics(sb)

```

```{r}
rejections_scatter(sb, supplementary=FALSE)
```

```{r}
plotFDRMethodsOverlap(sb, alpha=0.05, nsets=ncol(sb), order.by="freq", decreasing=TRUE, supplementary=FALSE)
```