---
title: "Benchmarking FDR Methods - Alternative Settings"
author: "Rafalab Journal Club Members"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    highlight: tango
    number_sections: true
    code_folding: hide
---

<!-- ######################################################################## -->
## Workspace Setup
<!-- ######################################################################## -->

```{r, load-libraries, message=FALSE}
library("dplyr")
library("ggplot2")
library("viridis")
library("data.table")
library("SummarizedBenchmark")
```

```{r, load-helper-functions}
source("../R/plotsim_standardize.R")
source("../R/plotsim_average.R")
source("../R/plotsim_single.R")
source("../R/rank_scatter.R")
source("../R/strat_hist.R")
```

<!-- ######################################################################## -->
## Plot Adjusted P-Values (1 replication)
<!-- ######################################################################## -->

```{r}
## list of results from 100 replication experiments
dl <- list.dirs("data-tsim/M1", recursive=FALSE, full.names=TRUE)

for (dd in dl) {
    fl <- list.files(dd, pattern=".rdata", full.names=TRUE)

    outp <- gsub("data", "plots", dd)
    dir.create(outp, showWarnings=FALSE, recursive=TRUE)
    
    ## generate same plots for all parameter settings
    for (f in fl) {
        ## read process data
        load(f)
        sba <- data.frame(assay(sb))

        ## for plots, only interested in Boca-Leek w/ 3 dof, IHw w/ alpha=0.05
        sbas <- select(sba, -c(`bl.df02`, `bl.df04`, `bl.df05`, `bonf`,
                               `ihw.a01`:`ihw.a04`, `ihw.a06`:`ihw.a10`))

        ## adjusted p-values vs. effect size
        gp <- plotsim_single(sbas, sim_df, "effect_size", TRUE)
        ggsave(paste0(outp, "/effectsize-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
               gp, width=10, height=9, units="in", dpi=200)

        ## adjusted p-values vs. independent covariate (uniformative)
        gp <- plotsim_single(sbas, sim_df, "ind_covariate", TRUE)
        ggsave(paste0(outp, "/indcov-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
               gp, width=10, height=9, units="in", dpi=200)

        ## adjusted p-values vs. standard error
        gp <- plotsim_single(sbas, sim_df, "SE", TRUE)
        ggsave(paste0(outp, "/SE-adjp-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
               gp, width=10, height=9, units="in", dpi=200)

        ## covariate rank vs. nlp (unadjusted)
        gp <- rank_scatter(sim_df, "pval", "ind_covariate") +
            scale_fill_viridis(option="viridis", direction=-1) +
            ggtitle("Informative Covariate Check")
        ggsave(paste0(outp, "/truep-heatmap-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
               gp, width=10, height=6, units="in", dpi=200)

        ## stratified covariate vs. nlp (unadjusted)
        gp <- strat_hist(sim_df, "pval", "ind_covariate", maxy=5) +
            ggtitle("Informative Covariate Check")
        ggsave(paste0(outp, "/truep-barchart-", gsub("(.*)\\.rdata", "\\1", basename(f)), ".png"),
               gp, width=10, height=4, units="in", dpi=200)
    }
}
```

<!-- ######################################################################## -->
## Plot Performance Metrics (100 replications)
<!-- ######################################################################## -->

```{r}
## list of results from 100 replication experiments
dl <- list.dirs("data-tsim/M100", recursive=FALSE, full.names=TRUE)

for (dd in dl) {
    fl <- list.files(dd, pattern=".rds", full.names=TRUE)

    outp <- gsub("data", "plots", dd)
    dir.create(outp, showWarnings=FALSE, recursive=TRUE)
    
    ## generate same plots for all parameter settings
    for (f in fl) {
        ## read process data
        res <- readRDS(f)
        tsb <- plotsim_standardize(res, alpha = seq(0.01, 0.10, 0.01))
        tsbs <- tsb %>%
            filter(!(blabel %in% c("bl-df02", "bl-df04", "bl-df05", "bonf"))) 

        ## look at FPR for Boca-Leek variations
        gp <- tsb %>%
            filter(grepl("^bl-", blabel)) %>%
            plotsim_average("FPR")
        ggsave(paste0(outp, "/FPR-bocaleek-",
                      gsub("(.*)\\.rds", "\\1", basename(f)), ".png"), gp,
               width=7, height=6, units="in", dpi=200)
        
        ## look at FPR for IHW variations
        gp <- tsb %>%
            filter(grepl("^ihw-", blabel)) %>%
            plotsim_average("FPR", merge_ihw = FALSE)
        ggsave(paste0(outp, "/FPR-ihw-",
                      gsub("(.*)\\.rds", "\\1", basename(f)), ".png"), gp,
               width=7, height=6, units="in", dpi=200)
        
        ## make plots for all metrics
        for (im in unique(tsbs$performanceMetric)) {
            gp <- plotsim_average(tsbs, im, clean_names = TRUE)
            ggsave(paste0(outp, "/", im, "-", gsub("(.*)\\.rds", "\\1", basename(f)), ".png"), gp,
                   width=7, height=6, units="in", dpi=200)
        }
    }
}
```






